#157 feat: Added Storybook
digdir/dialogporten-frontend pull request #177
Opened 2024-02-01 12:46 UTC by alexdigdir

## Description

## Related Issue(s)
- #{issue number}

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2024-02-01 12:49 UTC, TheKnarf commented on storybook/.eslintrc.cjs
> +module.exports = {
Since we're working on setting up `biome` as linter and formatter we could probably remove `eslint` from this PR?

2024-02-01 12:49 UTC, TheKnarf commented on storybook/package.json
> +    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
Same as above.

2024-02-02 08:49 UTC, seanes commented
Looks good to me! 

I encountered an issue (cf. below) running this locally with yarn. This seems to relevant to https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092 

Locking `jackspeak ` to `2.2.1` resolves the issue for me.

2024-02-02 13:58 UTC, TheKnarf approved these changes
👍

2024-02-02 13:59 UTC, TheKnarf requested changes
Check that storybook works

2024-02-02 14:05 UTC, TheKnarf approved these changes

2024-02-02 14:05 UTC, merged

2024-02-02 14:05 UTC, seanes approved these changes