Added Header component for desktop (#185)
digdir/dialogporten-frontend pull request #197
Opened 2024-02-09 11:35 UTC by alexdigdir

![CleanShot 2024-02-09 at 12 34 17](https://github.com/digdir/dialogporten-frontend/assets/144693023/de997c49-47b1-40a2-a37f-ad8261af9d8e)
![CleanShot 2024-02-09 at 12 34 54](https://github.com/digdir/dialogporten-frontend/assets/144693023/3365048c-8a7d-44f2-a7a5-f0fe3bc7ea67)

2024-02-09 12:08 UTC, seanes commented
Nice work - just a couple of questions / pointers that we all need to agree on.

2024-02-12 07:52 UTC, TheKnarf commented on packages/frontend-design-poc/src/components/Header/Header.tsx
> +/**
Shouldn't this be right above the component definition on line 30?

2024-02-12 07:53 UTC, TheKnarf commented on packages/storybook/src/stories/Header/Header.stories.ts
> +import { Header, HeaderProps } from '../../../../frontend-design-poc/src/components/Header/Header';
Could we figure out how to not do relative imports between packages before we have a ton of these?

2024-02-12 13:59 UTC, seanes requested changes

2024-02-13 11:52 UTC, merged