Added Sidebar (#186)
digdir/dialogporten-frontend pull request #217
Opened 2024-02-15 14:02 UTC by alexdigdir

For privatperson:
![CleanShot 2024-02-15 at 15 02 12](https://github.com/digdir/dialogporten-frontend/assets/144693023/ee491f31-df62-41da-a031-146edc1990b0)

For næringsdrivende:
![CleanShot 2024-02-15 at 15 02 28](https://github.com/digdir/dialogporten-frontend/assets/144693023/c096bf8a-8379-408a-b1f4-8f1723a722c6)

2024-02-16 07:11 UTC, seanes approved these changes
Ser fint ut! Småplukk og UU-ting kan vi ta senere.  Noen ting derimot som det er fint du ser på.

2024-02-16 07:47 UTC, TheKnarf commented on packages/storybook/src/stories/Sidebar/Sidebar.stories.tsx
> +import { HorizontalLine } from '../../../../frontend-design-poc/src/components/Sidebar/Sidebar';
Now that the PR on updated import statements are merged we might update the import statements in this PR.

2024-02-16 07:48 UTC, seanes commented on packages/storybook/src/stories/Sidebar/Sidebar.stories.tsx
> +import { HorizontalLine } from '../../../../frontend-design-poc/src/components/Sidebar/Sidebar';
Good point,  I missed that.

2024-02-16 07:53 UTC, seanes commented on packages/frontend-design-poc/src/components/SidebarItem/index.ts
SidebarItem and Sidebar imho should be grouped together, cf. InboxItems.

2024-02-16 07:55 UTC, seanes commented on packages/storybook/src/stories/Sidebar/Sidebar.stories.tsx
> +			<HorizontalLine />
I don't think I am very fond this being a separate component, to be honest.
It sounds very generic, but still has a very important role in the design of the Sidde bar. I would it make more sense to be a part of the SidebarItem, enabled through props?

2024-02-16 07:56 UTC, seanes commented on packages/frontend-design-poc/src/components/SidebarItem/SidebarItem.tsx
> +	url: string;
nitty, but `url` is misnomer, I way much prefer `path` (which it is)

2024-02-16 07:58 UTC, seanes requested changes
Se kommentarer

2024-02-16 08:14 UTC, TheKnarf commented on packages/storybook/src/stories/Sidebar/Sidebar.stories.tsx
> +			<HorizontalLine />
Here I disagree with @seanes. I think its a good idea to keep it as its own component.

2024-02-16 08:41 UTC, seanes commented on packages/storybook/src/stories/Sidebar/Sidebar.stories.tsx
> +			<HorizontalLine />
Just to clearify: Making it prop makes sense because it's not applicable to the last element. 
But OK, not a biggie for me.

2024-02-19 08:58 UTC, seanes commented on packages/frontend-design-poc/src/components/Sidebar/Sidebar.tsx
> +		<div className={styles.sidebar}>
Maybe i18n the strings right away? Would be nice.

2024-02-19 11:42 UTC, seanes approved these changes

2024-02-19 11:44 UTC, TheKnarf approved these changes

2024-02-19 12:20 UTC, merged