chore(github): add codeowners
digdir/dialogporten-frontend pull request #271
Opened 2024-02-29 12:31 UTC by arealmaas

## Hva er endret?

### Dokumentasjon / Storybook / testdekning

- [ ] Dokumentasjon er oppdatert eller ikke relevant / nødvendig.
- [ ] Ny komponent har en eller flere `stories` i `Storybook`, eller så er ikke dette relevant.
- [ ] Det er blitt lagt til nye tester / eksiterende tester er blitt utvidet, eller tester er ikke relevant.

### Skjermbilder eller GIFs (valgfritt)

2024-02-29 14:24 UTC, seanes submitted a review, later dismissed

2024-02-29 14:24 UTC, seanes commented
Nice!

2024-02-29 15:20 UTC, TheKnarf requested changes
Dobbel @@

2024-03-05 08:24 UTC, TheKnarf approved these changes

2024-03-05 08:26 UTC, merged