Chore(env) db connection string
digdir/dialogporten-frontend pull request #367
Opened 2024-03-27 11:45 UTC by seanes

henter db_connection_string fra .env fremfor å hardkode i compose.

## Hva er endret?

### Dokumentasjon / Storybook / testdekning

- [ ] Dokumentasjon er oppdatert eller ikke relevant / nødvendig.
- [ ] Ny komponent har en eller flere `stories` i `Storybook`, eller så er ikke dette relevant.
- [ ] Det er blitt lagt til nye tester / eksiterende tester er blitt utvidet, eller tester er ikke relevant.

### Skjermbilder eller GIFs (valgfritt)

2024-03-27 14:50 UTC, arealmaas commented on Readme.md
> +DB_CONNECTION_STRING=
burde kanskje legge inn den her som default? Eller gi en pekepinn på hva denne skal være når vi kjører opp compose `postgres://postgres:mysecretpassword@db:5432/dialogporten`

2024-03-27 14:50 UTC, arealmaas commented on packages/bff/src/data-source.ts
> +console.log('----- ConnectionOptions');
Vi burde nok ikke logge det her pga. at connection string blir med 🤔

2024-03-27 14:50 UTC, arealmaas commented on packages/bff/src/index.ts
> +    const { routes: authRoutes } = await import("./routes");
Om det kun er auth-routes burde vi kanskje rename fil til routes/auth eller auth-routes?

2024-04-02 11:05 UTC, TheKnarf requested changes
Not needed.

2024-04-02 11:07 UTC, closed without merging