feat(azure): add vnet (#453)
digdir/dialogporten-frontend pull request #498
Opened 2024-04-19 13:28 UTC by alexdigdir

## Hva er endret?
Lagt til lagring av søk.
Dette er kun lagret i local storage, persistering i backend kommer i egen oppgave.
![CleanShot 2024-04-19 at 15 23 49](https://github.com/digdir/dialogporten-frontend/assets/144693023/eeaf85ee-b700-46c9-bdd8-fdd89511d899)

 Related to https://github.com/digdir/dialogporten-frontend/issues/441

- Add a vnet to enable us to restrict traffic between redis/postgresql/containers within the a subnet

### Dokumentasjon / Storybook / testdekning

- [ ] Dokumentasjon er oppdatert eller ikke relevant / nødvendig.
- [ ] Ny komponent har en eller flere `stories` i `Storybook`, eller så er ikke dette relevant.
- [ ] Det er blitt lagt til nye tester / eksiterende tester er blitt utvidet, eller tester er ikke relevant.

### Skjermbilder eller GIFs (valgfritt)

## Hva er endret?

### Dokumentasjon / Storybook / testdekning

- [ ] Dokumentasjon er oppdatert eller ikke relevant / nødvendig.
- [ ] Ny komponent har en eller flere `stories` i `Storybook`, eller så er ikke dette relevant.
- [ ] Det er blitt lagt til nye tester / eksiterende tester er blitt utvidet, eller tester er ikke relevant.

### Skjermbilder eller GIFs (valgfritt)

2024-04-19 13:33 UTC, TheKnarf commented
Hvorfor heter PR'en `add vnet`?

2024-04-19 14:21 UTC, alexdigdir commented
> Hvorfor heter PR'en `add vnet`?

Er vel noe som har skjedd under rebase

2024-04-21 11:18 UTC, seanes commented on .azure/infrastructure/main.bicep
>      namePrefix: namePrefix
Skjønner helt hvorfor disse `.azure`-filene kom med her, sammen med litt annet snacks.

2024-04-21 11:19 UTC, seanes commented on .azure/infrastructure/main.bicep
> +    subnetId: vnet.outputs.subnetId
Prøve på ny rebase? Dette skulle vel fjernes.

2024-04-21 11:20 UTC, seanes commented on compose.yml
> +  # bff-graphql-poc:
Fjern kommentar, burde være fikset nå.

2024-04-21 11:22 UTC, seanes commented on packages/frontend-design-poc/src/components/FilterBar/AddFilterButton/SaveSearchButton.tsx
> +export const SaveSearchButton = ({ disabled, onBtnClick }: SaveSearchButtonProps) => {
Foreløpig så gir den ikke så fryktelig mye verdi, men antar denne skal ha litt logikk etter hvert, så sikkert greit. Litt usikker på plasseringen av filen, kanskje legge den i rot av Filterbar?

2024-04-21 11:23 UTC, seanes commented on packages/frontend-design-poc/src/components/FilterBar/AddFilterButton/SaveSearchButton.tsx
> +    <div>
fjern `div`

2024-04-21 11:27 UTC, seanes commented on packages/frontend-design-poc/src/components/FilterBar/FilterBar.tsx
> +      timestamp: new Date(),
datoer bør lagres som iso-strenger. så `.toISOString()` for da har man alltid en parsable representasjon som streng i UTC med offset.

2024-04-21 11:28 UTC, seanes commented on packages/frontend-design-poc/src/components/FilterBar/FilterBar.tsx
> +      id: Date.now(),
id kunne f.eks. vært en hash code av søk + aktive filtre, så er det lettere å sjekke om den er lagret senere bare ved å sjekke hash?

2024-04-21 11:30 UTC, seanes commented on packages/frontend-design-poc/src/components/FilterBar/FilterBar.tsx
> +      <SaveSearchButton onBtnClick={handleSaveSearch} disabled={!activeFilters?.length} />
Skal man ikke kunne lagre søk om det kun er en søkestreng?

2024-04-21 11:31 UTC, seanes commented on packages/frontend-design-poc/src/pages/Inbox/Inbox.tsx
> +  if (!decompressedString) throw new Error('Decompression failed');
`{ throw new Error ....}`

2024-04-21 11:33 UTC, seanes commented on packages/frontend-design-poc/src/pages/SavedSearches/savedSearches.module.css
> +    background: var(--Saved-Searches-Background);
En del units og noen farger som bryter med styleguiden vår her.

2024-04-21 11:33 UTC, seanes commented on packages/frontend-design-poc/src/pages/SavedSearches/SavedSearchesItem.tsx
> +  if (!savedSearch) return null;
{}

2024-04-21 11:34 UTC, seanes commented on packages/frontend-design-poc/src/pages/SavedSearches/SavedSearches.tsx
> +const autoFormatRelativeTime = (date: Date, locale = 'nb-NO'): string => {
hva er dette? kanskje vi burde dra inn `date-fns` til dette?

2024-04-23 09:39 UTC, alexdigdir commented on .azure/infrastructure/main.bicep
>      namePrefix: namePrefix
Ikke jeg heller, igjen, rebase som har fått med seg det. Jeg har ikke endret noe av det i det jeg har gjort.

2024-04-23 11:18 UTC, alexdigdir commented on packages/frontend-design-poc/src/components/FilterBar/FilterBar.tsx
> +      id: Date.now(),
Id her vil vel bli generert av databasen? Satte den til timestamp kun for testing, før persistering backend er på plass.

2024-04-23 11:23 UTC, alexdigdir commented on packages/frontend-design-poc/src/pages/SavedSearches/SavedSearchesItem.tsx
> +  if (!savedSearch) return null;
For the record: Jeg personlig liker ikke å legge til 2 ekstra linjer for ingenting. Men legger det inn.

2024-04-23 13:28 UTC, TheKnarf requested changes
Squash alt lokalt, og så fjern `.azure` mappa fra denne pr'en.

2024-04-23 13:37 UTC, TheKnarf commented on packages/frontend-design-poc/tsconfig.json
> +    // "noUnusedParameters": true,
Remove comments?

2024-04-23 17:18 UTC, seanes commented on packages/frontend-design-poc/src/pages/SavedSearches/SavedSearches.tsx
> +const autoFormatRelativeTime = (date: Date, locale = 'nb-NO'): string => {
jeg skjønner ikke helt hva funksjonen gjør, vanskelig å vite om timestamp er bedre da. når det gjelder lib, ja, vi må finne noe som ikke er så stort, kanskje ikke date-fns er et bra alternativ.

2024-04-24 08:17 UTC, TheKnarf approved these changes

2024-04-24 08:17 UTC, seanes approved these changes

2024-04-24 08:20 UTC, merged